data = {
    'Autor, Exequente, Impetrante ou Embargante': 'A1',
    'Réu, Executado, Impetrado ou Embargado': 'R2',
    'Fatos': 'F3',
    'Pedidos': 'P4',
    'Seguro Garantia': 'S5',
    'Vara Preventa': 'V6',
    'N° Processo Prevento': 'P7',
    'Data Distribuição Prevento': 'P8',
    'resumo perigo demora': 'R9',
    'resumo liminar': 'L10',
    'N° Auto de Infração': 'I11',
    'ID. Contestação': 'R12',
    'ID. Réplica': 'R13',
    'ID. Certidão': 'C14',
    'ID. Defere gratuidade': 'G15',
    'resumo contestação': 'RC16',
    'ID. Pedido genérico': 'VPG17',
    'nome do perito': 'W1',
    'data': 'W2',
    'ID. AR': 'W3',
    'ID. Resumo Bem Oferecido': 'RBO19',
    'ID. Parecer MP': 'MP20',
    'ID. Informações MS': 'IMS23',
    'ID. Documento': 'DI26',
    'ID. Intervenção Estado MS': 'I27',
    'Tipo de Ação': 'TAO32',
    'Tipo de sentença': 'TSA33',
    'ID. Sentença IDS34': 'IDS34',
    'resultado apelação': 'RAP35',
    'ID. acórdão': 'IDA36',
    'ID. certidão de trânsito': 'IDCT37',
    'data da prisão': 'DP38',
    'crime': 'CRI39',
    'vítima': 'VIT40',
    'ID manifestação Defensoria': 'IDDP41',
    'Ano do Último Pagamento': 'AUPA43',
    'Ano do Cancelamento da Inscrição': 'ACI44',
    'Exercícios Cobrados': 'EC45',
    'Exercício Extinto': 'EE46',
    'Número de Inscrição': 'NI47',
    'Saldo': 'VS42',
    'ID. Manifestação Réu': 'VMR18',
    'doença': 'VD19',
    'AJG': 'GJ20',
    'ID. agravo de instrumento': 'AI21',
    'ID. decisão em agravo de instrumento': 'DAI22',
    'Preliminares': 'PRE24',
    'ID. Embargos de desclaração': 'ED25',
    'ID. Mandado Oficial': 'MO28',
    'ID. cálculo': 'IDC29',
    'ID. Valor': 'V30',
    'Data e hora do ajuizamento': 'DHA31',
    'Despacho': 'INI32',
    'ID Petição': 'PET33',
    'Data inicial suspensão Intercorrente': 'DIS34',
    'Data final suspensão Intercorrente': 'DFS35',
    '1': 'CAMP1',
    '2': 'CAMP2',
    '3': 'CAMP3',
    '4': 'CAMP4',
    '5': 'CAMP5',
    '6': 'CAMP6',
}